const mongoose = require('mongoose');
const { Schema } = mongoose;

const AnnouncementSchema = new Schema({
    title: {
        type: String, 
        required: true,
        default: ''
    },
    content: {
        type: String, // This will store the HTML content generated by ReactQuill
        required: true,
    },
    audience: {
        type: String, // E.g., 'All Cellgroups' or 'Network Leaders'
        required: true
    },
    publishDate: {
        type: Date,
        required: true,
      },
      endDate: {
        type: Date,
        required: true,
      },
    announcementPic: { 
        type: String, 
        default: null 
    },
}, { timestamps: true });

const AnnouncementModel = mongoose.model('Announcements', AnnouncementSchema, 'Announcements');
module.exports = AnnouncementModel;