const mongoose = require('mongoose');
const { Schema } = mongoose;

const ArchiveAnnouncementSchema = new Schema({
    title: {
        type: String, 
        required: true,
        default: ''
    },
    content: {
        type: String, // This will store the HTML content generated by ReactQuill
        required: true,
    },
    audience: {
        type: String, // E.g., 'All Cellgroups' or 'Network Leaders'
        required: true
    },
    publishDate: {
        type: Date,
        required: true,
      },
      endDate: {
        type: Date,
        required: true,
      },
    announcementPic: { 
        type: String, 
        default: null 
    },
    
},{ timestamps: true });

const ArchivedAnnouncementModel = mongoose.model('ArchivedAnnouncement', ArchiveAnnouncementSchema, 'ArchivedAnnouncement');
module.exports = ArchivedAnnouncementModel;